packageExtensions:
    '@storybook/api@*':
        dependencies:
            regenerator-runtime: '*'
    '@storybook/core@*':
        dependencies:
            '@babel/core': '*'
    corejs-upgrade-webpack-plugin@*:
        dependencies:
            babel-runtime: ^6.26.0
            core-js: ^2.6.10
    '@chakra-ui/core@*':
        dependencies:
            '@babel/runtime': '*'
            'react-dom': '*'
    '@reach/component-component@*':
        dependencies:
            'prop-types': '*'
    '@reach/alert@*':
        dependencies:
            'prop-types': '*'
            'react-dom': '*'
    toasted-types@*:
        dependencies:
            'react-spring': '*'
    toasted-notes@*:
        dependencies:
            'react-spring': '*'
    babel-loader@*:
        dependencies:
            '@babel/core': '*'
    '@babel/plugin-proposal-async-generator-functions@*':
        dependencies:
            '@babel/core': '*'
    react-spring@*:
        dependencies:
            'react-dom': '*'
    '@apollographql/apollo-tools@*':
        dependencies:
            'graphql': '*'
    ws@*:
        dependencies:
            'bufferutil': '*'
            'utf-8-validate': '*'
    debug@*:
        dependencies:
            'supports-color': '*'
    node-fetch@*:
        dependencies:
            'encoding': '*'
    mongodb@*:
        dependencies:
            'mongodb-client-encryption': '*'
    node-pre-gyp@*:
        dependencies:
            'node-gyp': '*'
            'npm': '*'
            'request': '*'
            'aws-sdk': '*'
    promise-inflight@*:
        dependencies:
            'bluebird': '*'
    apollo-client@*:
        dependencies:
            'graphql': '*'
    '@apollo/client@*':
        dependencies:
            'graphql': '*'
    apollo-link-http-common@*:
        peerDependencies:
            'graphql': '*'
        dependencies:
            'graphql': '*'
    dotenv@*:
        dependencies:
            'fs': '*'
    '@apollo/react-hooks@*':
        dependencies:
            apollo-client: '*'
    apollo-cache-inmemory@*:
        dependencies:
            'graphql': '*'
    apollo-cache@*:
        dependencies:
            'graphql': '*'
    apollo-link@*:
        dependencies:
            'graphql': '*'
    apollo-tools@*:
        dependencies:
            'graphql': '*'
    apollo-utilities@*:
        dependencies:
            'graphql': '*'
    styled-components@*:
        dependencies:
            'react-is': '*'
    graphql-tag@*:
        dependencies:
            'graphql': '*'
        peerDependencies:
            'graphql': '*'
    ts-jest@*:
        dependencies:
            'jest-config': '*'
    '@babel/plugin-transform-typescript@*':
        peerDependencies:
            '@babel/core': '*'
        dependencies:
            '@babel/core': '*'

# pnpMode: 'loose'

checksumBehavior: 'ignore'
# plugins:
#     - path: .yarn/plugins/@yarnpkg/plugin-typescript.js
#       spec: '@yarnpkg/plugin-typescript'
#     - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.js
#       spec: '@yarnpkg/plugin-workspace-tools'

# yarnPath: /home/kenny/yarn/scripts/bin/yarn
