packageExtensions:
    '@storybook/api@*':
        dependencies:
            regenerator-runtime: '*'
    '@storybook/core@*':
        dependencies:
            '@babel/core': '*'
    corejs-upgrade-webpack-plugin@*:
        dependencies:
            babel-runtime: ^6.26.0
            core-js: ^2.6.10
    '@chakra-ui/core@*':
        dependencies:
            '@babel/runtime': '*'
    '@reach/component-component@*':
        dependencies:
            'prop-types': '*'
    '@reach/alert@*':
        dependencies:
            'prop-types': '*'
    toasted-types@*:
        dependencies:
            'react-spring': '*'
    toasted-notes@*:
        dependencies:
            'react-spring': '*'
# plugins:
#     - path: .yarn/plugins/@yarnpkg/plugin-typescript.js
#       spec: '@yarnpkg/plugin-typescript'
#     - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.js
#       spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: /home/kenny/yarn/scripts/bin/yarn
