name: GH Pages

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: '10.x'

            - name: Install Yarn Berry
              run: npm install -g yarn@berry

            - run: yarn --version

            # - name: Get yarn cache
            #   id: yarn-cache
            #   run: echo "::set-output name=dir::$(yarn cache dir)"

            # - name: Cache dependencies
            #   uses: actions/cache@v1
            #   with:
            #     path: ${{ steps.yarn-cache.outputs.dir }}
            #     key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
            #     restore-keys: |
            #       ${{ runner.os }}-yarn-

            - run: yarn install

            - name: Build
              run: yarn run docs

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./doc
                  publish_branch: gh-pages
                  force_orphan: true
